name: "examinis_student"
services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - selenium
      - postgres
    networks:
      - default
      - examinis_network
  
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
    networks:
      - default
  
  postgres:
    image: postgres:16.8
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      services:
  rabbitmq:
    container_name: examinis-rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - default
      - examinis_ai_network

volumes:
  postgres-data:
  rabbitmq_data:

networks:
  default:
  examinis_ai_network:
    name: examinis_ai_network
    driver: bridge
  examinis_network:
    external: true
