name: "examinis_student"
services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - selenium
      - postgres
    networks:
      - default
      - examinis_network
  
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
    networks:
      - default
  
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres-data:
  rabbitmq_data:

networks:
  default:
  examinis_network:
    external: true